interface YearClass {
  year: number;
  graduates: string[];
}

const akademiaGraduates: YearClass[] = [
  {
    year: 1999,
    graduates: [
      `Andrzej Łuczkowski`,
      `Bogumiła Knioła`,
      `Ewelina Fryc`,
      `Barbara Goerke`,
      `Piotr Godek`,
      `Dariusz Dobersztyn`,
      `Krystyna Esmont`,
      `Marek Jakubek`,
      `Sylwia Kraśnicka-Nowak`,
      `Roman Nowak`,
      `Maria Piotrowicz`,
      `Maria Radojewska`,
      `Krystyna Wiatr`,
    ],
  },
  {
    year: 2000,
    graduates: [
      `Krystyna Kosińska`,
      `Jerzy Pluta`,
      `Jolanta Szyszło`,
      `Teresa Smoczyńska`,
      `Aniela Kuptel`,
    ],
  },
  {
    year: 2001,
    graduates: [
      `Renata Zdrojewska`,
      `Ewa Ziętak`,
      `Teresa Tomaszewska-Dubowska`,
      `Teresa Jarkiewicz`,
      `Małgorzata Hak`,
      `Filip Adwent`,
      `Sławomir Kontowski`,
      ``,
      `Zdzisław Markowski`,
      `Andrzej Bednarczyk`,
      `Krzysztof Witenberg`,
    ],
  },
  {
    year: 2002,
    graduates: [
      `Cecylia Łuczaj`,
      `Tomasz Olejniczak`,
      `Mirosława Głowińska-Rybka`,
      `Barbara Aurast`,
      `Halina Kisielewska`,
      `Krzysztof Pająk`,
      `Piotr Kejna`,
      `Maciej Drozdowicz`,
      `Sławomir Barczyk`,
      `Jerzy Matheus`,
      `Aleksandra Świerzewska`,
      `Marcin Bożek`,
      ``,
      `Hans Lehmann`,
    ],
  },
  {
    year: 2003,
    graduates: [
      `Magdalena Wielgus`,
      `Elżbieta Bartczak`,
      `Anna Krantowska`,
      `Grażyna Sokołowska`,
      `Renata Prowadzisz`,
      `Katarzyna Turczyńska`,
      `Artur Markiewicz`,
      `Ihor Solowiow`,
      `Paweł Borowiński`,
      `Mirosław Koza`,
      `Andrzej Jabłoński`,
      `Robert Kozicki`,
      `Ireneusz Czapski`,
      `Cezary Krol`,
      `Mirosław Olszewski`,
      `Bohdan B. Maciejuk`,
      `Victor Soloviov`,
    ],
  },
  {
    year: 2004,
    graduates: [
      `Agnieszka Romanek`,
      `Roland Hadlich`,
      `Leszek Rogański`,
      `Joanna Krygier`,
      `Tadeusz Kloch`,
      `Janusz Zerbst`,
      `Henryk Perzanowski`,
      `Aleksander Olszewski`,
      `Paweł Widuliński`,
      `Krzysztof Szwabinski`,
      `Bronisław Zawada`,
      `Piotr Zborowski`,
      `Marek Kisiel`,
      `Roman Szymula`,
      `Andrzej Weryński`,
      `Katarzyna Jarkiewicz`,
      `Mirosława Kasierska`,
    ],
  },
  {
    year: 2005,
    graduates: [
      `Anna Piasecka-Pniewska`,
      `Wiesława Woźniak`,
      `Andrzej Baranowski`,
      `Robert Czaban`,
      `Cyprian Zduńczyk`,
      `Krzysztof Lukas`,
      `Kristina Andersen`,
      `Hans Erik Foldberg`,
      `Władysław Pustówka`,
      `Jerzy Zarębski`,
      `Katarzyna Józefiak`,
      `Wojciech Solis`,
      `Leszek Kwaśniewski`,
      `Władysław Ruchlewicz`,
      `Mieczysław Matejczyk`,
      `Michał Gawęda`,
      `Zdzisław Gabara`,
      `Małgorzta Guślakow`,
      `Michał Dolny`,
      `Wioletta Kołodziejczyk`,
      `Andrzej Chszczanowicz`,
      `Beata Piskozub`,
      `Bogdan Pączek`,
      `Maciej Budacki`,
      ``,
      `Janina Pisarska`,
      `Maria Kozłowska`,
      `Tadeusz Lempaszak`,
      `Liliana Skowron-Kuś`,
      `Renata Rygoł`,
      `Stanisław Grzesiak`,
      `Jerzy Smagur`,
      `Ewa Kuklewska`,
      `Anna Kołosowska`,
    ],
  },
  {
    year: 2006,
    graduates: [
      `Robert Michałowicz`,
      `Małgorzata Szmurło`,
      `Andrzej Filas`,
      `Ryszard Kłusewicz`,
      `Andrzej Rogowski`,
      `Irena Madeńska`,
      `Andrzej Kostkiewicz`,
      `Grażyna Pawlak`,
      `Magdalena Pacer`,
      `Łukasz Mazurek`,
      `Tomasz Kaźmierski`,
      `Piotr Sikorski`,
      `Marek Mleczko`,
      `Waldemar Krzemiński`,
      `Marcin Targański`,
      `Jarosław Grabski`,
      `Jacek Mosiniak`,
      `Jadwiga Szczotka`,
      `Anna Frydrychowicz`,
      `Andrzej Łakomiak`,
      `Beata Augustynowicz`,
      `Nijole Vencloviene`,
      `Anna Jasiulewicz`,
      `Mariusz Posłuszny`,
      `Iwona Jastrzębska`,
      `Jadwiga Anna Gardzilewicz`,
      `Ewa Kamińska`,
      `Robert Odrzywolski`,
      `Górski Zbigniew`,
      `Adrian Bugla`,
      `Kaniewski Jan`,
      `Szorc Stanisław`,
      `Mówiński Krzysztof`,
      `Świątek Joanna`,
      `Karolina Konicka`,
      `Waldemar Wójtowicz`,
      ``,
      `Jacek P. Boniatowski`,
      `Antoni Mazur`,
      `Andrzej Konkol`,
      `Anna Maliszewska`,
      `Posłuszny Bartosz`,
      `Matuszak Zuzanna`,
      `Adam Figeland`,
    ],
  },
];

const akademiaGraduatesNew: YearClass[] = [
  {
    year: 2007,
    graduates: [
      ``,
      `Dorota Pawełek`,
      `Krzysztof Kujawski`,
      `Piotr Grajewski`,
      `Jerzy Orlik`,
      `Bartosz Kłyszewski`,
      `Tomasz Orjan`,
      `Krzysztof Przybylski`,
      `Andrzej Wosik`,
      `Rafał Chodasz`,
      `Michał Guzek`,
    ],
  },
  {
    year: 2008,
    graduates: [
      `Zofia Trąbka`,
      `Roman Wojtarowicz`,
      `Marek Szarzyński`,
      `Leszek Szymański`,
      `Jerzy Rutkowski`,
      `Piotr Hoffman`,
      `Robert Pruszak`,
      `Robert Jabłoński`,
      `Aleksander Kubus`,
      `Grzegorz Rokicki`,
      `Katarzyna Ziółkowska`,
      `Aleksandra Charzyńska`,
      `Jacek Wenta`,
      `Marzena Waligóra`,
      `Anna Maria Kowalska`,
      `Michał Posłuszny`,
    ],
  },
  {
    year: 2009,
    graduates: [
      `Joanna Mejster`,
      ``,
      `Krzysztof Kaczmarczyk`,
      `Ewa Kamińska`,
      `Katarzyna Pielech`,
      `Wojciech Papajewski`,
      `Beata Kuchanny`,
      `Stefan Oleszczuk`,
      `Vadym Gorshkov`,
      `Krzysztof Selenta`,
      `Edwin Tomasz Roll`,
      `Magdalena Kowalska`,
      ``,
      `Aleksandra Maciszewska`,
      ``,
      ``,
      `Katarzyna Bieda`,
      `Artur Opolski`,
      `Grażyna Andrzejczak`,
      `Lucyna Łysakowska`,
      `Zbigniew Nawrocki`,
      `Joanna Łoza`,
      `Magdalena Adamska`,
      `Roman Jan Diechtiarow`,
      `Agnieszka Korpal`,
      `Hubert Minor`,
      `Oleszkiewicz Łukasz`,
      `Kania Aneta`,
      `Radwański Marcin`,
      `Józef Jerzy Zaręba`,
      `Piotr Głowacki`,
      `Andrzej Śmierz`,
      `Piotr Zimecki`,
    ],
  },
  {
    year: 2010,
    graduates: [
      `Olena Syrovatchenko`,
      `Dorota Prawdzik`,
      `Tomasz Kawa`,
      `Bartłomiej Mokrzycki`,
      `Wanda Nowicka`,
      `Marek Jarzyna`,
      `Marzenna Małgorzata Szklarska`,
      `Piotr Jańczuk`,
      `Iwona Gotłas`,
      `Rafał Dubaniewicz`,
      `Witold Gmurowski`,
      `Damian Lewandowski`,
      `Piotr Dumański`,
      `Justyna Galanek-Grabowska`,
      `Małgorzata Klarowska`,
      `Kuba Matuszak`,
      `Grzenkowicz Daniel`,
      `Tomasz Dyniec`,
      `Agnieszka Jaworowska`,
      `Paweł Tyka`,
      `Kołakowski Adam`,
      `Maiusz Głębocki`,
      `Rafał Buławicki`,
      `Hanna Burak`,
      `Mateusz Mikuła`,
      `Beata Jatkowska`,
      `Piaścik Anna`,
      `Kamil Bielas`,
      `Hanna Nowak`,
      `Elżbieta Sowa`,
      `Witold Przygoński`,
    ],
  },
  {
    year: 2011,
    graduates: [
      `Sławomir Jan Wojtkowiak`,
      `Przemysław Rybczyński`,
      `Szymczuk Martyna`,
      `Michał Mielczarek`,
      `Stanisław Nawrot`,
      `Stanisław Pikulski`,
      `Rafał Leks`,
      `Jolanta Lica`,
    ],
  },
  {
    year: 2012,
    graduates: [
      `Jakub Lewandowski`,
      `Remigiusz Janusz Markwordt`,
      `Mieczkowski Michał`,
      `Marek Józef Jabłoński`,
      `Jadwiga Stencel`,
    ],
  },
  {
    year: 2013,
    graduates: [
      `Daniel Mikoś`,
      `Sebastian Dudra`,
      `Agnieszka Maria Wiśnioch`,
      `Waldemar Marek Rybacki`,
      `Alicja Mielczarek`,
      `Michał Król`,
      `Dawid Kalinowski`,
      `Dariusz Stępniewicz`,
      `Jacek Krzysztof Trzciński`,
      `Sławomir Śpiewak`,
      `Mariusz Pełka`,
      `Wiesław Gąsiewski`,
      `Grzegorz Kiljanek`,
    ],
  },
  {
    year: 2014,
    graduates: [
      `Magdalena Maria Boroń`,
      `Piotr Wicik`,
      `Anna Cegłowska`,
      `Tomasz Kliche`,
      `Paulina Linda`,
      `Jacek Leszczyński`,
      `Arkadiusz Burczaniuk`,
      `Emil Frączek`,
      `Paweł Liszcz`,
    ],
  },
  {
    year: 2015,
    graduates: [
      `Józef Kazimierski`,
      `Konrad Kazimierski`,
      `Mariusz Perek`,
      `Łukasz Dachtera`,
      `Mariusz Walkowiak`,
      `Adrian Kasprzak`,
      `Marcin Mińkowski`,
      `Marcin Sobota`,
      `Marcin Kamiński`,
      `Alicja Raczkowska`,
    ],
  },
  {
    year: 2016,
    graduates: [
      `Mariusz Dąbrowski`,
      `Marcin Cieliczka`,
      `Paweł Ordyński`,
      `Renata Mielewczyk`,
      `Alicja Mazurkiewicz`,
      `Rafał Nowicki`,
      `Krystian Nowak`,
      `Laura Lis`,
      `Sebastian Zieliński`,
    ],
  },
  {
    year: 2017,
    graduates: [
      `Mariusz Antonowicz`,
      `Tomasz Walczak`,
      `Sylwia Górska`,
      `Jerzy Filipek`,
      `Sebastian Kozłowski`,
      ``,
      `Andrzej Mierzejewski`,
      `Konrad Korzeniewski`,
      `Tomasz Popik`,
      `Andrzej Szurlej`,
      `Ryszard Grzebyk`,
      `Maksymilian Kwiatkowski`,
      `Dominik Bajda`,
      `Kamil Rządkowski`,
      `Roman Niedzielski`,
      `Jonasz Koch`,
      `Robert Górski`,
    ],
  },
  {
    year: 2018,
    graduates: [
      `Michał Kraul`,
      `Bożena Mularz`,
      `Jan Wnęk`,
      `Anna Renusz`,
      `Kamil Król`,
      `Paweł Kołodziej`,
      `Maciej Maciejewski`,
      `Monika Bieżuńska`,
    ],
  },
  {
    year: 2019,
    graduates: [
      `Piotr Kostrzębski`,
      `Damian Korpoliński`,
      `Krzysztof Gołubski`,
      `Paweł Włoch`,
      `Tomasz Szulc`,
      `Katarzyna Gniewek`,
      `Marta Bryja`,
      `Łukasz Szarek`,
      `Michał Leski`,
      `Monika Matysiak`,
      `Katarzyna Olek`,
      `Michał Bartkowiak`,
      `Dominik Gorlicki`,
      `Jarosław Lipiński`,
      `Zbigniew Szymański`,
    ],
  },
  {
    year: 2021,
    graduates: [
      `Pavel Černiavskij`,
      `Leszek Gibas`,
      `Krzysztof Rogowski`,
      `Agnieszka Słonka`,
      `Piotr Wysocki`,
      `Joanna Jadwiga Żelazny`,
      ``,
      `Leszek Sochal`,
      ``,
      ``,
      `Michał Łukowski`,
      `Alicja Szumełda`,
      `Zuzanna Sikora`,
      `Hubert Hojan`,
      `Tomasz Jurecki`,
      `Martyna Romanek`,
      `Zofia Majcherczyk`,
      `Wiktoria Hańczyc`,
      `Kamil Szczęsny`,
      `Krystian Bugnacki`,
    ],
  },
  {
    year: 2022,
    graduates: [
      `Mariusz Auguścik`,
      `Grażyna Popko`,
      `Paulina Biedka`,
      `Kinga Kłos`,
      `Katarzyna Sochacka`,
      `Oliwia Koszela`,
      `Dariusz Król`,
      `Piotr Duszyński`,
    ],
  },
];

export { akademiaGraduates, akademiaGraduatesNew };
