interface YearClass {
  year: number;
  graduates: string[];
}

const akademiaGraduates: YearClass[] = [
  {
    year: 1999,
    graduates: [
      `Andrzej Łuczkowski`,
      `Bogumiła Knioła`,
      `Ewelina Fryc`,
      `Barbara Goerke`,
      `Piotr Godek`,
      `Dariusz Dobersztyn`,
      `Krystyna Esmont`,
      `Marek Jakubek`,
      `Sylwia Kraśnicka-Nowak`,
      `Roman Nowak`,
      `Maria Piotrowicz`,
      `Maria Radojewska`,
      `Krystyna Wiatr`,
    ],
  },
  {
    year: 2000,
    graduates: [
      `Krystyna Kosińska`,
      `Jerzy Pluta`,
      `Jolanta Szyszło`,
      `Teresa Smoczyńska`,
      `Aniela Kuptel`,
    ],
  },
  {
    year: 2001,
    graduates: [
      `Renata Zdrojewska`,
      `Ewa Ziętak`,
      `Teresa Tomaszewska-Dubowska`,
      `Teresa Jarkiewicz`,
      `Małgorzata Hak`,
      `Filip Adwent`,
      `Sławomir Kontowski`,
      `Zdzisław Markowski`,
      `Andrzej Bednarczyk`,
      `Krzysztof Witenberg`,
    ],
  },
  {
    year: 2002,
    graduates: [
      `Cecylia Łuczaj`,
      `Tomasz Olejniczak`,
      `Mirosława Głowińska-Rybka`,
      `Barbara Aurast`,
      `Halina Kisielewska`,
      `Krzysztof Pająk`,
      `Piotr Kejna`,
      `Maciej Drozdowicz`,
      `Sławomir Barczyk`,
      `Jerzy Matheus`,
      `Aleksandra Świerzewska`,
      `Marcin Bożek`,
      `Hans Lehmann`,
    ],
  },
  {
    year: 2003,
    graduates: [
      `Magdalena Wielgus`,
      `Elżbieta Bartczak`,
      `Anna Krantowska`,
      `Grażyna Sokołowska`,
      `Renata Prowadzisz`,
      `Katarzyna Turczyńska`,
      `Artur Markiewicz`,
      `Ihor Solowiow`,
      `Paweł Borowiński`,
      `Mirosław Koza`,
      `Andrzej Jabłoński`,
      `Robert Kozicki`,
      `Ireneusz Czapski`,
      `Cezary Krol`,
      `Mirosław Olszewski`,
      `Bohdan B. Maciejuk`,
      `Victor Soloviov`,
    ],
  },
  {
    year: 2004,
    graduates: [
      `Agnieszka Romanek`,
      `Roland Hadlich`,
      `Leszek Rogański`,
      `Joanna Krygier`,
      `Tadeusz Kloch`,
      `Janusz Zerbst`,
      `Henryk Perzanowski`,
      `Aleksander Olszewski`,
      `Paweł Widuliński`,
      `Krzysztof Szwabinski`,
      `Bronisław Zawada`,
      `Piotr Zborowski`,
      `Marek Kisiel`,
      `Roman Szymula`,
      `Andrzej Weryński`,
      `Katarzyna Jarkiewicz`,
      `Mirosława Kasierska`,
    ],
  },
  {
    year: 2005,
    graduates: [
      `Anna Piasecka-Pniewska`,
      `Wiesława Woźniak`,
      `Andrzej Baranowski`,
      `Robert Czaban`,
      `Cyprian Zduńczyk`,
      `Krzysztof Lukas`,
      `Kristina Andersen`,
      `Hans Erik Foldberg`,
      `Władysław Pustówka`,
      `Jerzy Zarębski`,
      `Katarzyna Józefiak`,
      `Wojciech Solis`,
      `Leszek Kwaśniewski`,
      `Władysław Ruchlewicz`,
      `Mieczysław Matejczyk`,
      `Michał Gawęda`,
      `Zdzisław Gabara`,
      `Małgorzta Guślakow`,
      `Michał Dolny`,
      `Wioletta Kołodziejczyk`,
      `Andrzej Chszczanowicz`,
      `Beata Piskozub`,
      `Bogdan Pączek`,
      `Maciej Budacki`,
      ``,
      `Janina Pisarska`,
      `Maria Kozłowska`,
      `Tadeusz Lempaszak`,
      `Liliana Skowron-Kuś`,
      `Renata Rygoł`,
      `Stanisław Grzesiak`,
      `Jerzy Smagur`,
      `Ewa Kuklewska`,
      `Anna Kołosowska`,
    ],
  },
  {
    year: 2006,
    graduates: [
      `Robert Michałowicz`,
      `Małgorzata Szmurło`,
      `Andrzej Filas`,
      `Ryszard Kłusewicz`,
      `Andrzej Rogowski`,
      `Irena Madeńska`,
      `Andrzej Kostkiewicz`,
      `Grażyna Pawlak`,
      `Magdalena Pacer`,
      `Łukasz Mazurek`,
      `Tomasz Kaźmierski`,
      `Piotr Sikorski`,
      `Marek Mleczko`,
      `Waldemar Krzemiński`,
      `Marcin Targański`,
      `Jarosław Grabski`,
      `Jacek Mosiniak`,
      `Jadwiga Szczotka`,
      `Anna Frydrychowicz`,
      `Andrzej Łakomiak`,
      `Beata Augustynowicz`,
      `Nijole Vencloviene`,
      `Anna Jasiulewicz`,
      `Mariusz Posłuszny`,
      `Iwona Jastrzębska`,
      `Jadwiga Anna Gardzilewicz`,
      `Ewa Kamińska`,
      `Robert Odrzywolski`,
      `Górski Zbigniew`,
      `Adrian Bugla`,
      `Kaniewski Jan`,
      `Szorc Stanisław`,
      `Mówiński Krzysztof`,
      `Świątek Joanna`,
      `Karolina Konicka`,
      `Waldemar Wójtowicz`,
      ``,
      `Jacek P. Boniatowski`,
      `Antoni Mazur`,
      `Andrzej Konkol`,
      `Anna Maliszewska`,
      `Posłuszny Bartosz`,
      `Matuszak Zuzanna`,
      `Adam Figeland`,
    ],
  },
];

const akademiaGraduatesNew: YearClass[] = [
  {
    year: 2007,
    graduates: [
      `Dorota Pawełek`,
      `Krzysztof Kujawski`,
      `Piotr Grajewski`,
      `Jerzy Orlik`,
      `Bartosz Kłyszewski`,
      `Tomasz Orjan`,
      `Krzysztof Przybylski`,
      `Andrzej Wosik`,
      `Rafał Chodasz`,
      `Michał Guzek`,
    ],
  },
];

export { akademiaGraduates, akademiaGraduatesNew };
